/**
 * Application i18n configuration
 * Auto-generated by @shelchin/svelte-i18n CLI
 *
 * This file handles translation imports and i18n setup
 * Using unified API with type safety for translation keys
 */
export declare const i18n: any;
export declare function getI18n(): any;
export default i18n;
